// Route constants

export const ROUTES = {
  HOME: "/",
  SETTING: "/settings",
  PROFILE: "/profile",
  NOTES: "/notes",
  SIGNUP: "/sign-up",
  SIGNIN: "/sign-in",
  VERIFYCODE: "/verify-code",
  NOTES_SUBJECT: "/notes/:subject",
  RESET_PASSWORD: "/reset-password",
  OVERVIEW: "/overview",
  FEEDBACK: "/feedback",
  PDF: "/pdf",
  COURSE: "/course",
  UPLOAD_NOTES: "/upload-notes",
  UPDATE_NOTES: "/update-notes",
  MANAGE_COURSE: "/manage-course",
  COURSE_USERS: "/course-users",
  COMMENT: "/comment/:notesId",
  ADD_DAILY_NOTES: "/add-daily-notes",
  LIST_DAILY_NOTES: "/list-daily-notes",
  DAILY_NOTES: "/daily-notes/:subject",
  UPDATE_DAILY_NOTES: "/update-daily-notes",
  CREATE_PDF: "/create-pdf",
  EDIT_PDF: "/edit-pdf",
};
